# Generated by Django 4.1.2 on 2023-07-02 05:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodShopWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
