# Generated by Django 4.1.2 on 2023-07-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodShopWebsite', '0002_homemodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homemodel',
            old_name='slug',
            new_name='Home_slug',
        ),
    ]
