# Generated by Django 4.1.2 on 2023-07-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodShopWebsite', '0004_dishesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
