# Generated by Django 4.1.2 on 2023-07-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodShopWebsite', '0005_homemodel_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DishesModel',
        ),
    ]
