# Generated by Django 4.1.2 on 2023-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodShopWebsite', '0006_delete_dishesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('Desc', models.TextField()),
                ('delivery', models.CharField(max_length=300)),
                ('payment', models.CharField(max_length=300)),
                ('service', models.CharField(max_length=300)),
            ],
        ),
    ]
