# Generated by Django 4.1.2 on 2023-07-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodShopWebsite', '0008_menumodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menumodel',
            old_name='Home_slug',
            new_name='menu_slug',
        ),
    ]
