# Generated by Django 4.1.2 on 2023-07-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodShopWebsite', '0011_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
